name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Ant (if build.xml exists)
        if: ${{ hashFiles('build.xml') != '' }}
        run: |
          sudo apt-get update && sudo apt-get install -y ant
          ant -noinput -buildfile build.xml
